name: mysql_crud_flutter
description: A new Flutter project.
publish_to: 'none' 


environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.2
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
